
import java.awt.Color;
import javax.swing.JOptionPane;

/*
Oracle Java Tutorials: "How to Use Tables - Selection Listeners"

NetBeans Help: "GUI Builder Connection Wizard: Select Source Event"
 */
public class FormularioGato extends javax.swing.JFrame {

    /**
     * Creates new form PanelConsulta
     */
    public FormularioGato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        FormularioGato = new javax.swing.JTabbedPane();
        DatosReporte = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtIdReporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoReporte = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtFechaTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblZonaReporte = new javax.swing.JLabel();
        txtZonaReporte = new javax.swing.JTextField();
        lblErrorIdReporte = new javax.swing.JLabel();
        lblErrorFechaTexto = new javax.swing.JLabel();
        lblErrorZonaReporte = new javax.swing.JLabel();
        DatosCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIdReportante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoContacto = new javax.swing.JTextField();
        txtNombreCompleto = new javax.swing.JTextField();
        lblErrorIdReportante = new javax.swing.JLabel();
        lblErrorNombreCompleto = new javax.swing.JLabel();
        lblErrorTelefonoContacto = new javax.swing.JLabel();
        DatosGato = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtColorPrincipal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMicrochip = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSeniasParticulares = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblRaza = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        lblTipoPelaje = new javax.swing.JLabel();
        cmbTipoPelaje = new javax.swing.JComboBox<>();
        lblEsterilizado = new javax.swing.JLabel();
        chkEsterilizado = new javax.swing.JCheckBox();
        lblErrorNombre = new javax.swing.JLabel();
        lblErrorColorPrincipal = new javax.swing.JLabel();
        lblErrorMicrochip = new javax.swing.JLabel();
        lblErrorSeniasParticulares = new javax.swing.JLabel();
        lblErrorRaza = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormularioGato.setAutoscrolls(true);
        FormularioGato.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FormularioGato.setPreferredSize(new java.awt.Dimension(900, 900));
        FormularioGato.setRequestFocusEnabled(false);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("ID Reporte (REP-0001)");
        jLabel13.setToolTipText("");
        jLabel13.setName("lblIdReporte"); // NOI18N

        txtIdReporte.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtIdReporte.setName("txtIdReporte"); // NOI18N
        txtIdReporte.setPreferredSize(new java.awt.Dimension(190, 40));
        txtIdReporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdReporteFocusLost(evt);
            }
        });
        txtIdReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdReporteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Tipo:");
        jLabel4.setName("lblTipoReporte"); // NOI18N

        cmbTipoReporte.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmbTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDR", "ENC" }));
        cmbTipoReporte.setSelectedIndex(-1);
        cmbTipoReporte.setName("cmbTipoReporte"); // NOI18N
        cmbTipoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoReporteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("Fecha del reporte:");
        jLabel14.setName("lblFechaReporte"); // NOI18N

        txtFechaTexto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtFechaTexto.setName("txtFechaTexto"); // NOI18N
        txtFechaTexto.setPreferredSize(new java.awt.Dimension(90, 40));
        txtFechaTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaTextoFocusLost(evt);
            }
        });
        txtFechaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaTextoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Formato \"dd/MM/yyyy\"");

        lblZonaReporte.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblZonaReporte.setText("Zona Reporte:");

        txtZonaReporte.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtZonaReporte.setMinimumSize(new java.awt.Dimension(36, 36));
        txtZonaReporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtZonaReporteFocusLost(evt);
            }
        });

        lblErrorIdReporte.setForeground(java.awt.Color.red);

        lblErrorFechaTexto.setForeground(java.awt.Color.red);
        lblErrorFechaTexto.setToolTipText("");

        lblErrorZonaReporte.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout DatosReporteLayout = new javax.swing.GroupLayout(DatosReporte);
        DatosReporte.setLayout(DatosReporteLayout);
        DatosReporteLayout.setHorizontalGroup(
            DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosReporteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1)
                    .addComponent(lblZonaReporte))
                .addGap(95, 95, 95)
                .addGroup(DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorZonaReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorFechaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorIdReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(cmbTipoReporte, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtZonaReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(207, 207, 207))
        );
        DatosReporteLayout.setVerticalGroup(
            DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosReporteLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtIdReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorIdReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTipoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosReporteLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(DatosReporteLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(txtFechaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(lblErrorFechaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(DatosReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZonaReporte)
                    .addComponent(txtZonaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorZonaReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        FormularioGato.addTab("Datos Reporte", DatosReporte);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Cédula:");
        jLabel5.setName("lblIdReportante"); // NOI18N

        txtIdReportante.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtIdReportante.setName("txtIdReportante"); // NOI18N
        txtIdReportante.setPreferredSize(new java.awt.Dimension(190, 40));
        txtIdReportante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdReportanteFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Nombre completo:");
        jLabel6.setName("lblNombreCompleto"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Teléfono:");
        jLabel7.setName("lblTelefonoContacto"); // NOI18N

        txtTelefonoContacto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtTelefonoContacto.setName("txtTelefonoContacto"); // NOI18N
        txtTelefonoContacto.setPreferredSize(new java.awt.Dimension(190, 40));
        txtTelefonoContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoContactoFocusLost(evt);
            }
        });

        txtNombreCompleto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombreCompleto.setName("txtNombreCompleto"); // NOI18N
        txtNombreCompleto.setPreferredSize(new java.awt.Dimension(190, 40));
        txtNombreCompleto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreCompletoFocusLost(evt);
            }
        });
        txtNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompletoActionPerformed(evt);
            }
        });

        lblErrorIdReportante.setForeground(java.awt.Color.red);

        lblErrorNombreCompleto.setForeground(java.awt.Color.red);
        lblErrorNombreCompleto.setPreferredSize(new java.awt.Dimension(190, 40));

        lblErrorTelefonoContacto.setForeground(java.awt.Color.red);
        lblErrorTelefonoContacto.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout DatosClienteLayout = new javax.swing.GroupLayout(DatosCliente);
        DatosCliente.setLayout(DatosClienteLayout);
        DatosClienteLayout.setHorizontalGroup(
            DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosClienteLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorTelefonoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdReportante, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(txtTelefonoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorIdReportante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblErrorNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228))
        );
        DatosClienteLayout.setVerticalGroup(
            DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosClienteLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdReportante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorIdReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        FormularioGato.addTab("Datos Cliente", DatosCliente);

        DatosGato.setPreferredSize(new java.awt.Dimension(900, 900));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Color:");
        jLabel9.setName("txtColor"); // NOI18N

        txtColorPrincipal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtColorPrincipal.setName("txtColorPrincipal"); // NOI18N
        txtColorPrincipal.setPreferredSize(new java.awt.Dimension(190, 40));
        txtColorPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorPrincipalFocusLost(evt);
            }
        });
        txtColorPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorPrincipalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Microchip:");
        jLabel11.setToolTipText("");
        jLabel11.setName("lblMicrochip"); // NOI18N

        txtMicrochip.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtMicrochip.setName("txtMicrochip"); // NOI18N
        txtMicrochip.setPreferredSize(new java.awt.Dimension(190, 40));
        txtMicrochip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMicrochipFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Señas particulares:");
        jLabel10.setName("lblSenias"); // NOI18N

        txtSeniasParticulares.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtSeniasParticulares.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSeniasParticulares.setName("txtSeniasParticulares"); // NOI18N
        txtSeniasParticulares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSeniasParticularesFocusLost(evt);
            }
        });
        txtSeniasParticulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeniasParticularesActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Nombre mascota:");
        jLabel12.setName("lblNombre"); // NOI18N

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(190, 40));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblRaza.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRaza.setText("Raza:");

        txtRaza.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtRaza.setPreferredSize(new java.awt.Dimension(190, 40));
        txtRaza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazaFocusLost(evt);
            }
        });

        lblTipoPelaje.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTipoPelaje.setText("Tipo de pelaje:");

        cmbTipoPelaje.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmbTipoPelaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corto", "Largo" }));
        cmbTipoPelaje.setSelectedIndex(-1);

        lblEsterilizado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEsterilizado.setText("¿Esterilizado?:");

        chkEsterilizado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkEsterilizado.setText("Sí");
        chkEsterilizado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkEsterilizadoItemStateChanged(evt);
            }
        });
        chkEsterilizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsterilizadoActionPerformed(evt);
            }
        });

        lblErrorNombre.setForeground(java.awt.Color.red);

        lblErrorColorPrincipal.setForeground(java.awt.Color.red);

        lblErrorMicrochip.setForeground(java.awt.Color.red);

        lblErrorSeniasParticulares.setForeground(java.awt.Color.red);

        lblErrorRaza.setForeground(java.awt.Color.red);

        btnGuardar.setBackground(java.awt.Color.green);
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnGuardar.setForeground(java.awt.Color.black);
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(java.awt.Color.red);
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosGatoLayout = new javax.swing.GroupLayout(DatosGato);
        DatosGato.setLayout(DatosGatoLayout);
        DatosGatoLayout.setHorizontalGroup(
            DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGatoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(lblRaza)
                    .addComponent(lblEsterilizado)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(lblTipoPelaje))
                .addGap(92, 92, 92)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosGatoLayout.createSequentialGroup()
                        .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMicrochip, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(txtSeniasParticulares)
                            .addComponent(txtColorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipoPelaje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorColorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorMicrochip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorSeniasParticulares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblErrorRaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(142, 142, 142))
                    .addGroup(DatosGatoLayout.createSequentialGroup()
                        .addComponent(chkEsterilizado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(DatosGatoLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(btnGuardar)
                .addGap(75, 75, 75)
                .addComponent(btnCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DatosGatoLayout.setVerticalGroup(
            DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosGatoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtColorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(lblErrorColorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtSeniasParticulares, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblErrorSeniasParticulares, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRaza)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipoPelaje)
                    .addComponent(cmbTipoPelaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEsterilizado)
                    .addComponent(chkEsterilizado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(DatosGatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        FormularioGato.addTab("Datos Mascota", DatosGato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FormularioGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(FormularioGato, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        FormularioGato.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            
            //Recolectar datos de Reporte
             String idReporte = txtIdReporte.getText();
             String fechaTexto = txtFechaTexto.getText();
             String tipo = cmbTipoReporte.getSelectedItem().toString();
             String zonaReporte = txtZonaReporte.getText();
            
             // Crear cliente
             Cliente cliente = new Cliente (
                txtNombreCompleto.getText(),
                txtIdReportante.getText(),
                txtTelefonoContacto.getText()  
             );
             
             //Crear Gato
             Mascota mascota = new Gato(
                    "CAT",
                    txtColorPrincipal.getText(),
                    txtSeniasParticulares.getText(),
                    txtMicrochip.getText(),
                    txtNombre.getText(),
                    txtRaza.getText(),
                    cmbTipoPelaje.getSelectedItem().toString(),
                    chkEsterilizado.isSelected()
            );
                 
                
            //Crear reporte segun tipo
            ReporteMascota reporte;
                if ("PDR".equals(tipo)){
                    reporte = new ReportePerdida(idReporte, fechaTexto, false, zonaReporte, cliente, mascota);

                }else{
                    reporte = new ReporteEncontrada(idReporte, fechaTexto, false, zonaReporte, cliente, mascota);                    

                }

            //5. Guardar usando GestorArchivos
            GestorArchivos gestor = new GestorArchivos();
                gestor.guardarReporte(reporte);
            //6.Confirmacion al usuario
                JOptionPane.showMessageDialog(this, "Reporte guardado exitosamente!");
                
            //7. CERRAR formulario y volver al menú
                this.dispose();
                new VentanaPrincipal().setVisible(true);

        } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Error de validación:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error inesperado: \n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
            
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void chkEsterilizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsterilizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEsterilizadoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtSeniasParticularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeniasParticularesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeniasParticularesActionPerformed

    private void txtColorPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorPrincipalActionPerformed

    private void txtNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompletoActionPerformed

    private void txtFechaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaTextoActionPerformed

    private void cmbTipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoReporteActionPerformed

    private void txtIdReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdReporteActionPerformed

    private void txtIdReporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdReporteFocusLost
        String texto = txtIdReporte.getText().trim();
        
        if(texto.isEmpty()){
            //campo vacio? tira error, campo obligatorio...
            txtIdReporte.setBackground(new Color(255, 200, 200));
            lblErrorIdReporte.setText("ID Reporte es obligatorio");
            lblErrorIdReporte.setForeground(Color.RED);
            return;
        }
        
        try {
            //Crear objeto Reporte segun eleccion
            ReporteMascota reporteTest;
            if ("PDR".equals(cmbTipoReporte.getSelectedItem().toString())) {
                reporteTest = new ReportePerdida();
            } else {
                reporteTest = new ReporteEncontrada();
            }
            
            reporteTest.setIdReporte(texto);
            
            //Si pasa la validacion
            txtIdReporte.setBackground(Color.WHITE);
            lblErrorIdReporte.setText("Formato Correcto");
            lblErrorIdReporte.setForeground(Color.BLUE);
        } catch (IllegalArgumentException e) {
            //Si no pasa la validacion
            txtIdReporte.setBackground(new Color (255, 200, 200)); //*se supone sea como rojo claro..
            lblErrorIdReporte.setText("Error " + e.getMessage());
            lblErrorIdReporte.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtIdReporteFocusLost

    private void txtFechaTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaTextoFocusLost
        String texto = txtFechaTexto.getText().trim();
        
        if (texto.isEmpty()){
            txtFechaTexto.setBackground(Color.WHITE);
            lblErrorFechaTexto.setText("Usará fecha actual");
            lblErrorFechaTexto.setForeground(Color.BLUE);
            return;
        }
        
        try {
            //Crear objeto Reporte segun eleccion
            ReporteMascota reporteTest;
            if ("PDR".equals(cmbTipoReporte.getSelectedItem().toString())) {
                reporteTest = new ReportePerdida();
            } else {
                reporteTest = new ReporteEncontrada();
            }
            
            reporteTest.setFechaReporte(texto);
            
            
            //Fecha valida
            txtFechaTexto.setBackground(Color.WHITE);
            lblErrorFechaTexto.setText("Fecha Válida");
            lblErrorFechaTexto.setForeground(Color.BLUE);
            
        } catch (IllegalArgumentException e) {
            //error
            txtFechaTexto.setBackground(new Color(255, 200, 200));
            lblErrorFechaTexto.setText("Error " + e.getMessage());
            lblErrorFechaTexto.setForeground(Color.RED);
            
        }
    }//GEN-LAST:event_txtFechaTextoFocusLost

    private void txtZonaReporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZonaReporteFocusLost
        String texto = txtZonaReporte.getText().trim();

        if (texto.isEmpty()) {
            txtZonaReporte.setBackground(new Color(255, 200, 200));
            lblErrorZonaReporte.setText("Zona es obligatoria");
            return;
        }

        try {
            ReporteMascota reporteTest;
            if ("PDR".equals(cmbTipoReporte.getSelectedItem().toString())) {
                reporteTest = new ReportePerdida();
            } else {
                reporteTest = new ReporteEncontrada();
            }

            reporteTest.setZonaReporte(texto);

            txtZonaReporte.setBackground(Color.WHITE);
            lblErrorZonaReporte.setText("Zona válida");
            lblErrorZonaReporte.setForeground(Color.BLUE);

        } catch (IllegalArgumentException e) {
            txtZonaReporte.setBackground(new Color(255, 200, 200));
            lblErrorZonaReporte.setText("Error " + e.getMessage());
            lblErrorZonaReporte.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtZonaReporteFocusLost

    private void txtIdReportanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdReportanteFocusLost
        String texto = txtIdReportante.getText().trim();
        
        if(texto.isEmpty()){
            txtIdReportante.setBackground(new Color (255, 200, 200));
            lblErrorIdReportante.setText("Cédula obligatoria");
            return;   
        }
        
        try {
            Cliente clienteTest = new Cliente ();
            clienteTest.setIdReportante(texto);
            
            txtIdReportante.setBackground(Color.WHITE);
            lblErrorIdReportante.setText("Cédula válida");
            lblErrorIdReportante.setForeground(Color.BLUE);
            
        } catch (IllegalArgumentException e){
            txtIdReportante.setBackground(new Color (255, 200,200));
            lblErrorIdReportante.setText("Error " + e.getMessage());
            lblErrorIdReportante.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtIdReportanteFocusLost

    private void txtNombreCompletoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreCompletoFocusLost
        String texto = txtNombreCompleto.getText().trim();
        
        if(texto.isEmpty()){
            txtNombreCompleto.setBackground(new Color (255, 200, 200));
            lblErrorNombreCompleto.setText("Nombre obligatorio");
            return;   
        }
        
        try {
            Cliente clienteTest = new Cliente ();
            clienteTest.setNombreCompleto(texto);
            
            txtNombreCompleto.setBackground(Color.WHITE);
            lblErrorNombreCompleto.setText("Nombre válido");
            lblErrorNombreCompleto.setForeground(Color.BLUE);
            
        } catch (IllegalArgumentException e){
            txtNombreCompleto.setBackground(new Color (255, 200,200));
            lblErrorNombreCompleto.setText("Error " + e.getMessage());
            lblErrorNombreCompleto.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtNombreCompletoFocusLost

    private void txtTelefonoContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoContactoFocusLost
        String texto = txtTelefonoContacto.getText().trim();
        
        if(texto.isEmpty()){
            txtTelefonoContacto.setBackground(new Color (255, 200, 200));
            lblErrorTelefonoContacto.setText("Teléfono obligatorio");
            return;   
        }
        
        try {
            Cliente clienteTest = new Cliente ();
            clienteTest.setTelefonoContacto(texto);
            
            txtTelefonoContacto.setBackground(Color.WHITE);
            lblErrorTelefonoContacto.setText("Teléfono válido");
            lblErrorTelefonoContacto.setForeground(Color.BLUE);
            
        } catch (IllegalArgumentException e){
            txtTelefonoContacto.setBackground(new Color (255, 200,200));
            lblErrorTelefonoContacto.setText("Error " + e.getMessage());
            lblErrorTelefonoContacto.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtTelefonoContactoFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        String texto = txtNombre.getText().trim();
    
        // CAMPO OPCIONAL - si está vacío, NO debe marcar error
        if (texto.isEmpty()) {
            txtNombre.setBackground(Color.WHITE);  
            lblErrorNombre.setText("");  
            return;
        }

        try {
            // Solo valida si NO está vacío
            Mascota mascotaTest = new Perro();
            mascotaTest.setNombre(texto);  // ← ¡Ojo! Es el nombre de la mascota

            txtNombre.setBackground(Color.WHITE);
            lblErrorNombre.setText("Nombre válido");
            lblErrorNombre.setForeground(Color.BLUE);

        } catch (IllegalArgumentException e) {
            txtNombre.setBackground(new Color(255, 200, 200));
            lblErrorNombre.setText("Error " + e.getMessage());
            lblErrorNombre.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtColorPrincipalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorPrincipalFocusLost
       String texto = txtColorPrincipal.getText().trim();
    
        if (texto.isEmpty()) {
            txtColorPrincipal.setBackground(new Color(255, 200, 200));
            lblErrorColorPrincipal.setText("Color obligatorio");
            lblErrorColorPrincipal.setForeground(Color.RED);
            return;
        }

        try {
            // Usar validación existente de Mascota
            Mascota mascotaTest = new Perro(); 
            mascotaTest.setColorPrincipal(texto);

            txtColorPrincipal.setBackground(Color.WHITE);
            lblErrorColorPrincipal.setText("Color válido");
            lblErrorColorPrincipal.setForeground(Color.BLUE);

        } catch (IllegalArgumentException e) {
            txtColorPrincipal.setBackground(new Color(255, 200, 200));
            lblErrorColorPrincipal.setText("Error " + e.getMessage());
            lblErrorColorPrincipal.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtColorPrincipalFocusLost

    private void txtMicrochipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMicrochipFocusLost
        String texto = txtMicrochip.getText().trim();
        if (texto.isEmpty()) {
            txtMicrochip.setBackground(Color.WHITE);  
            lblErrorMicrochip.setText("");  
            return;
        }

        try {
            // Solo valida si NO está vacío
            Mascota mascotaTest = new Perro();
            mascotaTest.setMicrochip(texto);  

            txtMicrochip.setBackground(Color.WHITE);
            lblErrorMicrochip.setText("Microchip válido");
            lblErrorMicrochip.setForeground(Color.BLUE);

        } catch (IllegalArgumentException e) {
            txtMicrochip.setBackground(new Color(255, 200, 200));
            lblErrorMicrochip.setText("Error " + e.getMessage());
            lblErrorMicrochip.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtMicrochipFocusLost

    private void txtSeniasParticularesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeniasParticularesFocusLost
        String texto = txtSeniasParticulares.getText().trim();
    
        if (texto.isEmpty()) {
            txtSeniasParticulares.setBackground(new Color(255, 200, 200));
            lblErrorSeniasParticulares.setText("Señas particulares obligatorias");
            lblErrorColorPrincipal.setForeground(Color.RED);
            return;
        }

        try {
            Mascota mascotaTest = new Perro();
            mascotaTest.setSeniasParticulares(texto);

            txtSeniasParticulares.setBackground(Color.WHITE);
            lblErrorSeniasParticulares.setText("Señas particulares válidas");
            lblErrorSeniasParticulares.setForeground(Color.BLUE);

        } catch (IllegalArgumentException e) {
            txtSeniasParticulares.setBackground(new Color(255, 200, 200));
            lblErrorSeniasParticulares.setText("Error " + e.getMessage());
            lblErrorSeniasParticulares.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtSeniasParticularesFocusLost

    private void txtRazaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaFocusLost
        String texto = txtRaza.getText().trim();
        if (texto.isEmpty()) {
            txtRaza.setBackground(Color.WHITE);  
            lblErrorRaza.setText("");  
            return;
        }

        try {
            // Solo valida si NO está vacío
            Perro perroTest = new Perro();
            perroTest.setRaza(texto);  

            txtRaza.setBackground(Color.WHITE);
            lblErrorRaza.setText("Raza válida");
            lblErrorRaza.setForeground(Color.BLUE);

        } catch (IllegalArgumentException e) {
            txtRaza.setBackground(new Color(255, 200, 200));
            lblErrorRaza.setText("Error " + e.getMessage());
            lblErrorRaza.setForeground(Color.RED);
        }
    }//GEN-LAST:event_txtRazaFocusLost

    private void chkEsterilizadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkEsterilizadoItemStateChanged
        boolean Esterilizado = chkEsterilizado.isSelected();
    }//GEN-LAST:event_chkEsterilizadoItemStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPerro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPerro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosCliente;
    private javax.swing.JPanel DatosGato;
    private javax.swing.JPanel DatosReporte;
    private javax.swing.JTabbedPane FormularioGato;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkEsterilizado;
    private javax.swing.JComboBox<String> cmbTipoPelaje;
    private javax.swing.JComboBox<String> cmbTipoReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorColorPrincipal;
    private javax.swing.JLabel lblErrorFechaTexto;
    private javax.swing.JLabel lblErrorIdReportante;
    private javax.swing.JLabel lblErrorIdReporte;
    private javax.swing.JLabel lblErrorMicrochip;
    private javax.swing.JLabel lblErrorNombre;
    private javax.swing.JLabel lblErrorNombreCompleto;
    private javax.swing.JLabel lblErrorRaza;
    private javax.swing.JLabel lblErrorSeniasParticulares;
    private javax.swing.JLabel lblErrorTelefonoContacto;
    private javax.swing.JLabel lblErrorZonaReporte;
    private javax.swing.JLabel lblEsterilizado;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblTipoPelaje;
    private javax.swing.JLabel lblZonaReporte;
    private javax.swing.JTextField txtColorPrincipal;
    private javax.swing.JTextField txtFechaTexto;
    private javax.swing.JTextField txtIdReportante;
    private javax.swing.JTextField txtIdReporte;
    private javax.swing.JTextField txtMicrochip;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextField txtSeniasParticulares;
    private javax.swing.JTextField txtTelefonoContacto;
    private javax.swing.JTextField txtZonaReporte;
    // End of variables declaration//GEN-END:variables
}
