
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rosario
 */
public class VentanaPRUEBACONSULTAEDITAR extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPRUEBACONSULTAEDITAR
     */
    public VentanaPRUEBACONSULTAEDITAR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblZonaReporte = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbTalla = new javax.swing.JComboBox<>();
        chkTieneCollar = new javax.swing.JCheckBox();
        txtMicrochip = new javax.swing.JTextField();
        txtColorPrincipal = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNombreCompleto = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        txtZonaReporte = new javax.swing.JTextField();
        txtTelefonoContacto = new javax.swing.JTextField();
        lblTipoPelaje = new javax.swing.JLabel();
        cmbTipoPelaje = new javax.swing.JComboBox<>();
        lblEsterilizado = new javax.swing.JLabel();
        chkEsterilizado = new javax.swing.JCheckBox();
        txtSeniasParticulares = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtIdReporte = new javax.swing.JTextField();
        btnCargarDatos = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnValidarId = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtFechaTexto = new javax.swing.JTextField();
        cmbEspecie = new javax.swing.JComboBox<>();
        txtIdReportante = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        CambiarTipoReporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<>();
        txtValorBusqueda = new javax.swing.JTextField();
        btnBuscarReporte = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsultaReporteTipo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Nombre completo:");
        jLabel6.setName("lblNombreCompleto"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Teléfono:");
        jLabel7.setName("lblTelefonoContacto"); // NOI18N

        lblZonaReporte.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblZonaReporte.setText("Zona Reporte:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Nombre mascota:");
        jLabel12.setName("lblNombre"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Color:");
        jLabel9.setName("txtColor"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Microchip:");
        jLabel11.setToolTipText("");
        jLabel11.setName("lblMicrochip"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Señas particulares:");
        jLabel10.setName("lblSenias"); // NOI18N

        lblRaza.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRaza.setText("Raza:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Talla:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Collar:");

        cmbTalla.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmbTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEQ", "MED", "GRA" }));
        cmbTalla.setPreferredSize(new java.awt.Dimension(190, 40));

        chkTieneCollar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkTieneCollar.setText("Sí");
        chkTieneCollar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkTieneCollarItemStateChanged(evt);
            }
        });
        chkTieneCollar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTieneCollarActionPerformed(evt);
            }
        });

        txtMicrochip.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtMicrochip.setPreferredSize(new java.awt.Dimension(190, 40));
        txtMicrochip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMicrochipFocusLost(evt);
            }
        });
        txtMicrochip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMicrochipActionPerformed(evt);
            }
        });

        txtColorPrincipal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtColorPrincipal.setPreferredSize(new java.awt.Dimension(190, 40));
        txtColorPrincipal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorPrincipalFocusLost(evt);
            }
        });
        txtColorPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorPrincipalActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(190, 40));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtNombreCompleto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtNombreCompleto.setPreferredSize(new java.awt.Dimension(190, 40));
        txtNombreCompleto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreCompletoFocusLost(evt);
            }
        });
        txtNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompletoActionPerformed(evt);
            }
        });

        txtRaza.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtRaza.setPreferredSize(new java.awt.Dimension(190, 40));
        txtRaza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazaFocusLost(evt);
            }
        });
        txtRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaActionPerformed(evt);
            }
        });

        txtZonaReporte.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtZonaReporte.setPreferredSize(new java.awt.Dimension(190, 40));
        txtZonaReporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtZonaReporteFocusLost(evt);
            }
        });
        txtZonaReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZonaReporteActionPerformed(evt);
            }
        });

        txtTelefonoContacto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtTelefonoContacto.setPreferredSize(new java.awt.Dimension(190, 40));
        txtTelefonoContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoContactoFocusLost(evt);
            }
        });
        txtTelefonoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoContactoActionPerformed(evt);
            }
        });

        lblTipoPelaje.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTipoPelaje.setText("Tipo de pelaje:");

        cmbTipoPelaje.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmbTipoPelaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corto", "Largo" }));

        lblEsterilizado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEsterilizado.setText("¿Esterilizado?:");

        chkEsterilizado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        chkEsterilizado.setText("Sí");
        chkEsterilizado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkEsterilizadoItemStateChanged(evt);
            }
        });
        chkEsterilizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsterilizadoActionPerformed(evt);
            }
        });

        txtSeniasParticulares.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtSeniasParticulares.setPreferredSize(new java.awt.Dimension(190, 40));
        txtSeniasParticulares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSeniasParticularesFocusLost(evt);
            }
        });
        txtSeniasParticulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeniasParticularesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.blue);
        jLabel4.setText("Aplicable solo para perros:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.blue);
        jLabel8.setText("Aplicable solo para gatos:");

        btnGuardarCambios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Introduzca el ID a actualizar:");

        txtIdReporte.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtIdReporte.setName("txtIdReporte"); // NOI18N
        txtIdReporte.setPreferredSize(new java.awt.Dimension(190, 40));
        txtIdReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdReporteActionPerformed(evt);
            }
        });

        btnCargarDatos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCargarDatos.setText("Cargar informacion del reporte");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Desea cambiar el tipo de reporte del reporte ingresado?");

        btnValidarId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnValidarId.setText("Validar ID");
        btnValidarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarIdActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("Especie:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("Cédula:");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("Fecha del Reporte:");

        txtFechaTexto.setEditable(false);
        txtFechaTexto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        cmbEspecie.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cmbEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOG", "CAT" }));
        cmbEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEspecieActionPerformed(evt);
            }
        });

        txtIdReportante.setEditable(false);
        txtIdReportante.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtIdReportante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdReportanteActionPerformed(evt);
            }
        });

        txtEspecie.setEditable(false);
        txtEspecie.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar al menú");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        CambiarTipoReporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CambiarTipoReporte.setText("Carmbiar tipo");
        CambiarTipoReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarTipoReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(btnGuardarCambios)
                .addGap(46, 46, 46)
                .addComponent(btnRegresar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoPelaje)
                            .addComponent(lblEsterilizado))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkEsterilizado)
                            .addComponent(cmbTipoPelaje, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(380, 380, 380))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkTieneCollar)
                                    .addComponent(cmbTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRaza)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(lblZonaReporte)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtColorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                    .addComponent(txtZonaReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMicrochip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSeniasParticulares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtFechaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(48, 48, 48)
                                                .addComponent(txtIdReportante, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 790, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnValidarId))
                            .addComponent(btnCargarDatos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CambiarTipoReporte)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtIdReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValidarId))
                .addGap(32, 32, 32)
                .addComponent(btnCargarDatos)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addComponent(CambiarTipoReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblZonaReporte, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtZonaReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtIdReportante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtFechaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtColorPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(txtSeniasParticulares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaza)
                            .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoPelaje)
                            .addComponent(cmbTipoPelaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cmbTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEsterilizado)
                            .addComponent(chkEsterilizado)
                            .addComponent(jLabel3)
                            .addComponent(chkTieneCollar))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarCambios)
                            .addComponent(btnRegresar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cmbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Consultar y Editar reporte");

        cmbBuscarPor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Especie", "Zona" }));
        cmbBuscarPor.setSelectedIndex(-1);
        cmbBuscarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuscarPorActionPerformed(evt);
            }
        });

        txtValorBusqueda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtValorBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorBusquedaActionPerformed(evt);
            }
        });

        btnBuscarReporte.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBuscarReporte.setText("Buscar");
        btnBuscarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReporteActionPerformed(evt);
            }
        });

        tblConsultaReporteTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsultaReporteTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultaReporteTipoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblConsultaReporteTipo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(txtValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnBuscarReporte))
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarReporte))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1044, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkTieneCollarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkTieneCollarItemStateChanged
        boolean tieneCollar = chkTieneCollar.isSelected();
    }//GEN-LAST:event_chkTieneCollarItemStateChanged

    private void chkTieneCollarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTieneCollarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTieneCollarActionPerformed

    private void txtMicrochipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMicrochipFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMicrochipFocusLost

    private void txtMicrochipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMicrochipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMicrochipActionPerformed

    private void txtColorPrincipalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorPrincipalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorPrincipalFocusLost

    private void txtColorPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorPrincipalActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreCompletoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreCompletoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompletoFocusLost

    private void txtNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompletoActionPerformed

    private void txtRazaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaFocusLost

    private void txtRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaActionPerformed

    private void txtZonaReporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtZonaReporteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZonaReporteFocusLost

    private void txtZonaReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZonaReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZonaReporteActionPerformed

    private void txtTelefonoContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoContactoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoContactoFocusLost

    private void txtTelefonoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoContactoActionPerformed

    private void txtValorBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorBusquedaActionPerformed
         String texto = txtIdReporte.getText().trim();

        if(texto.isEmpty()){
            txtIdReporte.setBackground(new Color(255, 200, 200));
            JOptionPane.showMessageDialog(this, "Campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // SOLO validar formato - no importa el tipo
            ReporteMascota reporteTest = new ReportePerdida(); // o ReporteEncontrada, da igual
            reporteTest.setIdReporte(texto); // ← Solo esto valida el formato

            txtIdReporte.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(this, "Formato de ID válido!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (IllegalArgumentException e) {
            txtIdReporte.setBackground(new Color(255, 200, 200));
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtValorBusquedaActionPerformed

    private void btnBuscarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReporteActionPerformed
        try {
            //Aqui se leen el criterio y valor
            String criterio = cmbBuscarPor.getSelectedItem().toString();
            String valor = txtValorBusqueda.getText();
            
            //Validacion especie
            if ("Especie".equals(criterio)){
                Mascota mascotaTest = new Perro();
                mascotaTest.setEspecie(valor);
            }
            
            if ("Cédula".equals(criterio)){
                Cliente clienteTest = new Cliente();
                clienteTest.setIdReportante(valor);
            }

            // Cargar los datos y crear GestorReportes
            GestorArchivos gestor = new GestorArchivos();
            ArrayList<ReporteMascota> todosLosReportes = gestor.cargarTodosLosReportes();

            GestorReportes gestorReportes = new GestorReportes();
            gestorReportes.setListaReportes(todosLosReportes);

            //Ejecutar la busqueda
            ArrayList<ReporteMascota> resultados = gestorReportes.consultarPorCriterio(criterio, valor);

            //Modelo de la tabla
            String [] columnasTipo ={"Id Reporte", "Tipo de reporte","Fecha","Zona","Cédula", "Nombre Completo", "Teléfono", 
                "Especie", "Nombre", "Color", "Microchip", "Señas particulares", "Raza", "Talla", "Tipo Pelaje", "Collar", "Esterilizado"};
            DefaultTableModel modelTipo = new DefaultTableModel(columnasTipo, 0);

            //Llenando la tabla con los datos

            for (ReporteMascota reporte : resultados) {
                String raza = "";
                String talla = "";
                String tipoPelaje = ""; 
                String collarStr = "";
                String esterilizadoStr = "";

                if (reporte.getMascota() instanceof Perro) {
                    Perro perro = (Perro) reporte.getMascota();
                    raza = perro.getRaza();
                    talla = perro.getTalla();
                    collarStr = perro.isTieneCollar()  ? "Sí":"No" ;
                } else if (reporte.getMascota() instanceof Gato){
                    Gato gato = (Gato) reporte.getMascota();
                    raza = gato.getRaza();
                    tipoPelaje = gato.getTipoPelaje();
                    esterilizadoStr = gato.isEsterilizado()  ? "Sí":"No" ;
                }
                    
                modelTipo.addRow (new Object[] {
                    reporte.getIdReporte(),
                    reporte.getTipoReporte(),
                    reporte.getFechaFormateada(),
                    reporte.getZonaReporte(),
                    reporte.getCliente().getIdReportante(),
                    reporte.getCliente().getNombreCompleto(),
                    reporte.getCliente().getTelefonoContacto(),
                    reporte.getMascota().getEspecie(),
                    reporte.getMascota().getNombre(),
                    reporte.getMascota().getColorPrincipal(),
                    reporte.getMascota().getMicrochip(),
                    reporte.getMascota().getSeniasParticulares(),
                    raza, talla, tipoPelaje, collarStr, esterilizadoStr                     
                });
            }

            //Asignar los datos a la tabla
            tblConsultaReporteTipo.setModel(modelTipo);

            //Mensajes de confirmacion
            JOptionPane.showMessageDialog(this, "Datos cargados exitosamente: " + resultados.size() + " reportes", "Información cargada", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la información: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarReporteActionPerformed

    private void chkEsterilizadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkEsterilizadoItemStateChanged
        boolean Esterilizado = chkEsterilizado.isSelected();
    }//GEN-LAST:event_chkEsterilizadoItemStateChanged

    private void chkEsterilizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsterilizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEsterilizadoActionPerformed

    private void txtSeniasParticularesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeniasParticularesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeniasParticularesFocusLost

    private void txtSeniasParticularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeniasParticularesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeniasParticularesActionPerformed

    private void tblConsultaReporteTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaReporteTipoMouseClicked

            
    }//GEN-LAST:event_tblConsultaReporteTipoMouseClicked

    private void txtIdReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdReporteActionPerformed
     
        
       
    }//GEN-LAST:event_txtIdReporteActionPerformed

    private void btnValidarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarIdActionPerformed
        String texto = txtIdReporte.getText().trim();

        if(texto.isEmpty()){
            txtIdReporte.setBackground(new Color(255, 200, 200));
            JOptionPane.showMessageDialog(this, "Campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // SOLO validar formato - no importa el tipo
            ReporteMascota reporteTest = new ReportePerdida(); // o ReporteEncontrada, da igual
            reporteTest.setIdReporte(texto); // ← Solo esto valida el formato

            txtIdReporte.setBackground(Color.WHITE);
            JOptionPane.showMessageDialog(this, "Formato de ID válido!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (IllegalArgumentException e) {
            txtIdReporte.setBackground(new Color(255, 200, 200));
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnValidarIdActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
                                                     
    try {
        String idReporte = txtIdReporte.getText().trim();
        
        if (idReporte.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero cargue un reporte", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. CARGAR REPORTE ORIGINAL
        GestorArchivos gestorArchivos = new GestorArchivos();
        ArrayList<ReporteMascota> todos = gestorArchivos.cargarTodosLosReportes();
        GestorReportes gestorReportes = new GestorReportes();
        gestorReportes.setListaReportes(todos);
        
        ReporteMascota reporteOriginal = gestorReportes.buscarReportePorId(idReporte);
        if (reporteOriginal == null) {
            JOptionPane.showMessageDialog(this, "Primero cargue un reporte", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. CREAR OBJETOS CON DATOS ACTUALES
        Cliente clienteEditado = new Cliente(
            txtNombreCompleto.getText().trim(),
            reporteOriginal.getCliente().getIdReportante(),
            txtTelefonoContacto.getText().trim()
        );

        Mascota mascotaEditada;
        if (reporteOriginal.getMascota() instanceof Perro) {
            Perro perroOriginal = (Perro) reporteOriginal.getMascota();
            mascotaEditada = new Perro(
                perroOriginal.getEspecie(),
                txtColorPrincipal.getText().trim(),
                txtSeniasParticulares.getText().trim(),
                txtMicrochip.getText().trim(),
                txtNombre.getText().trim(),
                txtRaza.getText().trim(),
                cmbTalla.getSelectedItem().toString(),
                chkTieneCollar.isSelected()
            );
        } else {
            Gato gatoOriginal = (Gato) reporteOriginal.getMascota();
            mascotaEditada = new Gato(
                gatoOriginal.getEspecie(),
                txtColorPrincipal.getText().trim(),
                txtSeniasParticulares.getText().trim(),
                txtMicrochip.getText().trim(),
                txtNombre.getText().trim(),
                txtRaza.getText().trim(),
                cmbTipoPelaje.getSelectedItem().toString(),
                chkEsterilizado.isSelected()
            );
        }

        // 3. CREAR REPORTE TEMPORAL
        ReporteMascota nuevosDatos;
        if (reporteOriginal.getTipoReporte().equals("PDR")) {
            nuevosDatos = new ReportePerdida(
                idReporte,
                reporteOriginal.getFechaFormateada(),
                false,
                txtZonaReporte.getText().trim(),
                clienteEditado,
                mascotaEditada
            );
        } else {
            nuevosDatos = new ReporteEncontrada(
                idReporte,
                reporteOriginal.getFechaFormateada(),
                false,
                txtZonaReporte.getText().trim(),
                clienteEditado,
                mascotaEditada
            );
        }

        // 🆕 4. GUARDAR DIRECTAMENTE EN ARCHIVO (sin usar GestorReportes)
        gestorArchivos.eliminarReporte(idReporte);      // Elimina el viejo
        gestorArchivos.guardarReporte(nuevosDatos);     // Guarda el nuevo

        JOptionPane.showMessageDialog(this, "Cambios guardados exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        try {
            String idReporte = txtIdReporte.getText().trim();

            GestorArchivos gestor = new GestorArchivos();
            ArrayList<ReporteMascota> todos = gestor.cargarTodosLosReportes();
            GestorReportes gestorReportes = new GestorReportes();
            gestorReportes.setListaReportes(todos);

            // Llamando al metodo de busqueda por ID para llevenar
            ReporteMascota reporteOriginal = gestorReportes.buscarReportePorId(idReporte);

            if (reporteOriginal == null) {
                JOptionPane.showMessageDialog(this, "No se encontró el reporte", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Auto-llenar campos 
            txtIdReporte.setText(reporteOriginal.getIdReporte());
            txtIdReportante.setText(reporteOriginal.getCliente().getIdReportante()); 
            txtFechaTexto.setText(reporteOriginal.getFechaFormateada());
            txtNombreCompleto.setText(reporteOriginal.getCliente().getNombreCompleto());
            txtTelefonoContacto.setText(reporteOriginal.getCliente().getTelefonoContacto());
            txtZonaReporte.setText(reporteOriginal.getZonaReporte());
            txtColorPrincipal.setText(reporteOriginal.getMascota().getColorPrincipal());
            txtSeniasParticulares.setText(reporteOriginal.getMascota().getSeniasParticulares());
            txtNombre.setText(reporteOriginal.getMascota().getNombre());
            String especie = cmbEspecie.getSelectedItem().toString();
            txtEspecie.setText(especie);
            txtEspecie.setEditable(false);
            //Haciendo casting para cargar los datos especificos por raza
            if (reporteOriginal.getMascota() instanceof Perro) {
                Perro perro = (Perro) reporteOriginal.getMascota();
                txtRaza.setText(perro.getRaza());
                cmbTalla.setSelectedItem(perro.getTalla());
                chkTieneCollar.setSelected(perro.isTieneCollar());
            } else if (reporteOriginal.getMascota() instanceof Gato) {
                Gato gato = (Gato) reporteOriginal.getMascota();
                txtRaza.setText(gato.getRaza());
                cmbTipoPelaje.setSelectedItem(gato.getTipoPelaje());
                chkEsterilizado.setSelected(gato.isEsterilizado());
            }
            
            

            JOptionPane.showMessageDialog(this, "Datos cargados", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }       
        
        
        
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void txtIdReportanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdReportanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdReportanteActionPerformed

    private void cmbEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEspecieActionPerformed

    }//GEN-LAST:event_cmbEspecieActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieActionPerformed

    private void CambiarTipoReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarTipoReporteActionPerformed
         try {
        String idReporte = txtIdReporte.getText().trim();
        
        if (idReporte.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Primero cargue un reporte", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. Obtener tipo actual del reporte cargado
        GestorArchivos gestorArchivos = new GestorArchivos();
        ArrayList<ReporteMascota> todos = gestorArchivos.cargarTodosLosReportes();
        GestorReportes gestorReportes = new GestorReportes();
        gestorReportes.setListaReportes(todos);
        
        ReporteMascota reporte = gestorReportes.buscarReportePorId(idReporte);
        if (reporte == null) {
            JOptionPane.showMessageDialog(this, "Reporte no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String tipoActual = reporte.getTipoReporte();
        String nuevoTipo = tipoActual.equals("PDR") ? "ENC" : "PDR";

        // 2. Confirmar con el usuario
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Cambiar reporte de " + tipoActual + " a " + nuevoTipo + "?",
            "Confirmar cambio", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        // 3. Usar tu método joya
        boolean exito = gestorArchivos.moverReporteEntreArchivos(idReporte, nuevoTipo);
        
        if (exito) {
            JOptionPane.showMessageDialog(this, 
                "✅ Reporte cambiado de " + tipoActual + " a " + nuevoTipo, 
                "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Opcional: recargar datos
            btnCargarDatosActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, 
                "❌ Error al cambiar tipo", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_CambiarTipoReporteActionPerformed

    private void cmbBuscarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBuscarPorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPRUEBACONSULTAEDITAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPRUEBACONSULTAEDITAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPRUEBACONSULTAEDITAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPRUEBACONSULTAEDITAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPRUEBACONSULTAEDITAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarTipoReporte;
    private javax.swing.JButton btnBuscarReporte;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnValidarId;
    private javax.swing.JCheckBox chkEsterilizado;
    private javax.swing.JCheckBox chkTieneCollar;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JComboBox<String> cmbEspecie;
    private javax.swing.JComboBox<String> cmbTalla;
    private javax.swing.JComboBox<String> cmbTipoPelaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEsterilizado;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblTipoPelaje;
    private javax.swing.JLabel lblZonaReporte;
    private javax.swing.JTable tblConsultaReporteTipo;
    private javax.swing.JTextField txtColorPrincipal;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtFechaTexto;
    private javax.swing.JTextField txtIdReportante;
    private javax.swing.JTextField txtIdReporte;
    private javax.swing.JTextField txtMicrochip;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextField txtSeniasParticulares;
    private javax.swing.JTextField txtTelefonoContacto;
    private javax.swing.JTextField txtValorBusqueda;
    private javax.swing.JTextField txtZonaReporte;
    // End of variables declaration//GEN-END:variables
}
