
import javax.swing.JOptionPane;

/*
Elvia Sanchez Leiva
9 de noviembre 2025.
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegistrarReporte = new javax.swing.JButton();
        btnConsultaryEditarReportes = new javax.swing.JButton();
        btnReporteGeneral = new javax.swing.JButton();
        btnCoincidencias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnReporteAgrupado = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("jLabel2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setInheritsPopupMenu(false);
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 56, 197));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));

        btnRegistrarReporte.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegistrarReporte.setText("🐕‍🐈  Registrar Reporte");
        btnRegistrarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarReporteActionPerformed(evt);
            }
        });

        btnConsultaryEditarReportes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConsultaryEditarReportes.setText("📑 Consultar y Editar Reportes");
        btnConsultaryEditarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaryEditarReportesActionPerformed(evt);
            }
        });

        btnReporteGeneral.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnReporteGeneral.setText("Reporte General");
        btnReporteGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteGeneralActionPerformed(evt);
            }
        });

        btnCoincidencias.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnCoincidencias.setText("💞 Coincidencias");
        btnCoincidencias.setToolTipText("");
        btnCoincidencias.setAutoscrolls(true);
        btnCoincidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoincidenciasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("🐾 Gestor de Reportes de Mascotas🐾");

        btnReporteAgrupado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnReporteAgrupado.setText("Reporte Agrupado");
        btnReporteAgrupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteAgrupadoActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(255, 132, 132));
        btnCerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultaryEditarReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(btnRegistrarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporteGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporteAgrupado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCoincidencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(btnRegistrarReporte)
                .addGap(18, 18, 18)
                .addComponent(btnConsultaryEditarReportes)
                .addGap(18, 18, 18)
                .addComponent(btnReporteGeneral)
                .addGap(18, 18, 18)
                .addComponent(btnReporteAgrupado)
                .addGap(18, 18, 18)
                .addComponent(btnCoincidencias)
                .addGap(94, 94, 94)
                .addComponent(btnCerrar)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoincidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoincidenciasActionPerformed
        new VentanaCoincidencias().setVisible(true);
    }//GEN-LAST:event_btnCoincidenciasActionPerformed

    private void btnReporteGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteGeneralActionPerformed
        new VentanaReporteGeneral().setVisible(true);    
    }//GEN-LAST:event_btnReporteGeneralActionPerformed

    private void btnConsultaryEditarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaryEditarReportesActionPerformed
        new VentanaPRUEBACONSULTAEDITAR().setVisible(true); 
    }//GEN-LAST:event_btnConsultaryEditarReportesActionPerformed

    private void btnRegistrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarReporteActionPerformed
        //Abri formulario de registro
        new VentanaSeleccionEspecie().setVisible(true);
    }//GEN-LAST:event_btnRegistrarReporteActionPerformed

    private void btnReporteAgrupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteAgrupadoActionPerformed
        new VentanaReporteAgrupados().setVisible(true);        
    }//GEN-LAST:event_btnReporteAgrupadoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCoincidencias;
    private javax.swing.JButton btnConsultaryEditarReportes;
    private javax.swing.JButton btnRegistrarReporte;
    private javax.swing.JButton btnReporteAgrupado;
    private javax.swing.JButton btnReporteGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
