
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
Elvia Sanchez Leiva
9 de noviembre 2025.
 */
public class VentanaReporteAgrupados extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReporteGeneral
     */
    public VentanaReporteAgrupados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSubirInformacionEspecie = new javax.swing.JButton();
        jPorTipo = new javax.swing.JScrollPane();
        tblReportePorTipo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSubirInformacionTipo = new javax.swing.JButton();
        jPorEspecie = new javax.swing.JScrollPane();
        tblReportePorEspecie = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnSubirInformacionEspecie.setText("Subir información");
        btnSubirInformacionEspecie.setToolTipText("");
        btnSubirInformacionEspecie.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSubirInformacionEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirInformacionEspecieActionPerformed(evt);
            }
        });

        tblReportePorTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPorTipo.setViewportView(tblReportePorTipo);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte Agrupado");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("Por especie:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setText("Por tipo:");

        btnSubirInformacionTipo.setText("Subir información");
        btnSubirInformacionTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirInformacionTipoActionPerformed(evt);
            }
        });

        tblReportePorEspecie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPorEspecie.setViewportView(tblReportePorEspecie);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPorEspecie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPorTipo, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(btnSubirInformacionTipo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(btnSubirInformacionEspecie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubirInformacionTipo)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPorEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnSubirInformacionEspecie)
                .addGap(487, 487, 487))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        btnRegresar.setText("Regresar al menú");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void btnSubirInformacionEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirInformacionEspecieActionPerformed
        try {
            //Subir archivos
            GestorArchivos gestor = new GestorArchivos();
            ArrayList <ReporteMascota> todosLosReportes = gestor.cargarTodosLosReportes();
            
            //Crear gestorReportes y pasarle los datos
            GestorReportes gestorReportes = new GestorReportes();
            gestorReportes.setListaReportes(todosLosReportes);
            
            //Conteo sobre todos los reportes para contar perros y gatos 
            
            int dogCount =0;
            int catCount = 0;
            
            for (ReporteMascota reporte : todosLosReportes){
                if ( "DOG".equals(reporte.getMascota().getEspecie())){
                    dogCount++;
                } 
                if ("CAT".equals(reporte.getMascota().getEspecie())){
                        catCount++;
                }
            }

            //Modelo para tabla tipos
            String [] columnasTipo = {"Especie","Cantidad"};
            DefaultTableModel modelTipo = new DefaultTableModel(columnasTipo, 0);
            
            //Para llenar las tablas
            modelTipo.addRow(new Object[]{"DOG", dogCount});
            modelTipo.addRow(new Object[]{"CAT", catCount});
            
            //De modelo a la tabla
            tblReportePorEspecie.setModel(modelTipo);
            
            //Mensaje de confirmacion
            JOptionPane.showMessageDialog(this, "Datos cargados exitosamente: " + todosLosReportes.size() + " reportes", "Información cargada", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la información: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubirInformacionEspecieActionPerformed

    private void btnSubirInformacionTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirInformacionTipoActionPerformed
        try {
            //Subir archivos
            GestorArchivos gestor = new GestorArchivos();
            ArrayList <ReporteMascota> todosLosReportes = gestor.cargarTodosLosReportes();
            
            //Crear gestorReportes y pasarle los datos
            GestorReportes gestorReportes = new GestorReportes();
            gestorReportes.setListaReportes(todosLosReportes);
            
            //Tabla tipos
            int pdrCount = gestorReportes.obtenerPerdidos().size();
            int encCount = gestorReportes.obtenerEncontrados().size();
            
            //Modelo para tabla tipos
            String [] columnasTipo = {"Tipo","Cantidad"};
            DefaultTableModel modelTipo = new DefaultTableModel(columnasTipo, 0);
            
            //Para llenar las tablas
            modelTipo.addRow(new Object[]{"PDR", pdrCount});
            modelTipo.addRow(new Object[]{"ENC", encCount});
            
            //Asignar modelo a la tabla
            tblReportePorTipo.setModel(modelTipo);
            
            //Mensaje de confirmacion
            JOptionPane.showMessageDialog(this, "Datos cargados exitosamente: " + todosLosReportes.size() + " reportes", "Información cargada", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error " + e.getMessage(), "Error ", JOptionPane.ERROR_MESSAGE); 
        
        }
    }//GEN-LAST:event_btnSubirInformacionTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReporteAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReporteAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReporteAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReporteAgrupados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReporteAgrupados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSubirInformacionEspecie;
    private javax.swing.JButton btnSubirInformacionTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jPorEspecie;
    private javax.swing.JScrollPane jPorTipo;
    private javax.swing.JTable tblReportePorEspecie;
    private javax.swing.JTable tblReportePorTipo;
    // End of variables declaration//GEN-END:variables
}
